add permission: android.permission.INTERNET
Fixes force close when sideloading a downloaded apk from the notification panel
java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/my_downloads/831 from pid=25212, uid=10019 requires android.permission.INTERNET, or grantUriPermission()

Change-Id: I31a4efa8dfebd2af52333e249f21e7e64ed5c854